config/routes.rb
Snarf::Application.routes.draw do
  resources :export_runs

  resources :blobs

  resources :export_records

  resources :data_sources

  root :to => 'data_sources#index'

  mount ApiV1 => '/'
  mount ApiV2 => '/'

end

app/models/data_source.rb
class DataSource < ActiveRecord::Base
  attr_accessible :name

  validates :name, :presence => true, :uniqueness => true
  has_many :export_records, :dependent => :destroy
  has_many :export_runs, :dependent => :destroy

end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  # GET /data_sources
  # GET /data_sources.json
  def index
    @data_sources = DataSource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @data_sources }
    end
  end

  # GET /data_sources/1
  # GET /data_sources/1.json
  def show
    @data_source = DataSource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @data_source }
    end
  end

  # GET /data_sources/new
  # GET /data_sources/new.json
  def new
    @data_source = DataSource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @data_source }
    end
  end

  # GET /data_sources/1/edit
  def edit
    @data_source = DataSource.find(params[:id])
  end

  # POST /data_sources
  # POST /data_sources.json
  def create
    @data_source = DataSource.new(params[:data_source])

    respond_to do |format|
      if @data_source.save
        format.html { redirect_to @data_source, notice: 'Data source was successfully created.' }
        format.json { render json: @data_source, status: :created, location: @data_source }
      else
        format.html { render action: "new" }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /data_sources/1
  # PUT /data_sources/1.json
  def update
    @data_source = DataSource.find(params[:id])

    respond_to do |format|
      if @data_source.update_attributes(params[:data_source])
        format.html { redirect_to @data_source, notice: 'Data source was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sources/1
  # DELETE /data_sources/1.json
  def destroy
    @data_source = DataSource.find(params[:id])
    @data_source.destroy

    respond_to do |format|
      format.html { redirect_to data_sources_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/data_sources/_form.html.erb
<%= form_for(@data_source) do |f| %>
  <% if @data_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_source.errors.count, "error") %> prohibited this data_source from being saved:</h2>

      <ul>
      <% @data_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_sources/edit.html.erb
<h1>Editing data_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_source %> |
<%= link_to 'Back', data_sources_path %>

app/views/data_sources/index.html.erb
<h1>Listing data_sources</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @data_sources.each do |data_source| %>
  <tr>
    <td><%= data_source.name %></td>
    <td><%= link_to 'Show', data_source %></td>
    <td><%= link_to 'Edit', edit_data_source_path(data_source) %></td>
    <td><%= link_to 'Destroy', data_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data source', new_data_source_path %>

app/views/data_sources/new.html.erb
<h1>New data_source</h1>

<%= render 'form' %>

<%= link_to 'Back', data_sources_path %>

app/views/data_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @data_source.name %>
</p>


<%= link_to 'Edit', edit_data_source_path(@data_source) %> |
<%= link_to 'Back', data_sources_path %>