config/routes.rb
Snarf::Application.routes.draw do
  resources :export_runs

  resources :blobs

  resources :export_records

  resources :data_sources

  root :to => 'data_sources#index'

  mount ApiV1 => '/'
  mount ApiV2 => '/'

end

app/models/blob.rb
class Blob < ActiveRecord::Base
  attr_accessible :checksum, :data

  validates :checksum, :presence => true, :uniqueness => true

  set_primary_key :checksum

  has_many :export_records, foreign_key: :checksum

  has_many :data_sources, through: :export_records

end

app/controllers/blobs_controller.rb
class BlobsController < ApplicationController
  # GET /blobs
  # GET /blobs.json
  def index
    @blobs = Blob.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blobs }
    end
  end

  # GET /blobs/1
  # GET /blobs/1.json
  def show
    @blob = Blob.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blob }
    end
  end

  # GET /blobs/new
  # GET /blobs/new.json
  def new
    @blob = Blob.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blob }
    end
  end

  # GET /blobs/1/edit
  def edit
    @blob = Blob.find(params[:id])
  end

  # POST /blobs
  # POST /blobs.json
  def create
    @blob = Blob.new(params[:blob])

    respond_to do |format|
      if @blob.save
        format.html { redirect_to @blob, notice: 'Blob was successfully created.' }
        format.json { render json: @blob, status: :created, location: @blob }
      else
        format.html { render action: "new" }
        format.json { render json: @blob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blobs/1
  # PUT /blobs/1.json
  def update
    @blob = Blob.find(params[:id])

    respond_to do |format|
      if @blob.update_attributes(params[:blob])
        format.html { redirect_to @blob, notice: 'Blob was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blobs/1
  # DELETE /blobs/1.json
  def destroy
    @blob = Blob.find(params[:id])
    @blob.destroy

    respond_to do |format|
      format.html { redirect_to blobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blobs_helper.rb
module BlobsHelper
end

app/views/blobs/_form.html.erb
<%= form_for(@blob) do |f| %>
  <% if @blob.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blob.errors.count, "error") %> prohibited this blob from being saved:</h2>

      <ul>
      <% @blob.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :checksum %><br />
    <%= f.text_field :checksum %>
  </div>
    <div class="field">
      <%= f.label :data %><br />
      <%= f.text_area :data %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blobs/edit.html.erb
<h1>Editing blob</h1>

<%= render 'form' %>

<%= link_to 'Show', @blob %> |
<%= link_to 'Back', blobs_path %>

app/views/blobs/index.html.erb
<h1>Listing blobs</h1>

<table>
  <tr>
    <th>Checksum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blobs.each do |blob| %>
  <tr>
    <td><%= blob.checksum %></td>
    <td><%= link_to 'Show', blob %></td>
    <td><%= link_to 'Edit', edit_blob_path(blob) %></td>
    <td><%= link_to 'Destroy', blob, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blob', new_blob_path %>

app/views/blobs/new.html.erb
<h1>New blob</h1>

<%= render 'form' %>

<%= link_to 'Back', blobs_path %>

app/views/blobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Checksum:</b>
  <%= @blob.checksum %>
</p>

<p>
  <b>Data:</b>
  <%= @blob.data %>
</p>

<%= link_to 'Edit', edit_blob_path(@blob) %> |
<%= link_to 'Back', blobs_path %>