config/routes.rb
Snarf::Application.routes.draw do
  resources :export_runs

  resources :blobs

  resources :export_records

  resources :data_sources

  root :to => 'data_sources#index'

  mount ApiV1 => '/'
  mount ApiV2 => '/'

end

app/models/export_record.rb
class ExportRecord < ActiveRecord::Base
  attr_accessible :checksum, :data_source_id, :primary_key

  validates_presence_of :checksum, :data_source_id, :primary_key

  belongs_to :data_source
  belongs_to :export_run

  belongs_to :blob, foreign_key: :checksum

end

app/controllers/export_records_controller.rb
class ExportRecordsController < ApplicationController
  # GET /export_records
  # GET /export_records.json
  def index
    @export_records = ExportRecord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @export_records }
    end
  end

  # GET /export_records/1
  # GET /export_records/1.json
  def show
    @export_record = ExportRecord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @export_record }
    end
  end

  # GET /export_records/new
  # GET /export_records/new.json
  def new
    @export_record = ExportRecord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @export_record }
    end
  end

  # GET /export_records/1/edit
  def edit
    @export_record = ExportRecord.find(params[:id])
  end

  # POST /export_records
  # POST /export_records.json
  def create
    @export_record = ExportRecord.new(params[:export_record])

    respond_to do |format|
      if @export_record.save
        format.html { redirect_to @export_record, notice: 'Export record was successfully created.' }
        format.json { render json: @export_record, status: :created, location: @export_record }
      else
        format.html { render action: "new" }
        format.json { render json: @export_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /export_records/1
  # PUT /export_records/1.json
  def update
    @export_record = ExportRecord.find(params[:id])

    respond_to do |format|
      if @export_record.update_attributes(params[:export_record])
        format.html { redirect_to @export_record, notice: 'Export record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @export_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /export_records/1
  # DELETE /export_records/1.json
  def destroy
    @export_record = ExportRecord.find(params[:id])
    @export_record.destroy

    respond_to do |format|
      format.html { redirect_to export_records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/export_records_helper.rb
module ExportRecordsHelper
end

app/views/export_records/_form.html.erb
<%= form_for(@export_record) do |f| %>
  <% if @export_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@export_record.errors.count, "error") %> prohibited this export_record from being saved:</h2>

      <ul>
      <% @export_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_source_id %><br />
    <%= f.number_field :data_source_id %>
  </div>
  <div class="field">
    <%= f.label :primary_key %><br />
    <%= f.text_field :primary_key %>
  </div>
  <div class="field">
    <%= f.label :checksum %><br />
    <%= f.text_field :checksum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/export_records/edit.html.erb
<h1>Editing export_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @export_record %> |
<%= link_to 'Back', export_records_path %>

app/views/export_records/index.html.erb
<h1>Listing export_records</h1>

<table>
  <tr>
    <th>Data source</th>
    <th>Primary key</th>
    <th>Checksum</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @export_records.each do |export_record| %>
  <tr>
    <td><%= export_record.data_source_id %></td>
    <td><%= export_record.primary_key %></td>
    <td><%= export_record.checksum %></td>
    <td><%= link_to 'Show', export_record %></td>
    <td><%= link_to 'Edit', edit_export_record_path(export_record) %></td>
    <td><%= link_to 'Destroy', export_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Export record', new_export_record_path %>

app/views/export_records/new.html.erb
<h1>New export_record</h1>

<%= render 'form' %>

<%= link_to 'Back', export_records_path %>

app/views/export_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data source:</b>
  <%= @export_record.data_source_id %>
</p>

<p>
  <b>Primary key:</b>
  <%= @export_record.primary_key %>
</p>

<p>
  <b>Checksum:</b>
  <%= @export_record.checksum %>
</p>


<%= link_to 'Edit', edit_export_record_path(@export_record) %> |
<%= link_to 'Back', export_records_path %>