config/routes.rb
Snarf::Application.routes.draw do
  resources :export_runs

  resources :blobs

  resources :export_records

  resources :data_sources

  root :to => 'data_sources#index'

  mount ApiV1 => '/'
  mount ApiV2 => '/'

end

app/models/export_run.rb
class ExportRun < ActiveRecord::Base
  attr_accessible :data_source_id, :duration, :finished_at, :record_count, :started_at

  belongs_to :data_source
  has_many :export_records

  before_save :update_duration

  validates :data_source_id, :presence => true
  validates :started_at, :presence => true
  validates :finished_at, :presence => true
  validates :record_count, :presence => true

  private

  def update_duration
    if !duration && finished_at && started_at
      self.duration = finished_at - started_at
    end
  end

end

app/controllers/export_runs_controller.rb
class ExportRunsController < ApplicationController
  # GET /export_runs
  # GET /export_runs.json
  def index
    @export_runs = ExportRun.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @export_runs }
    end
  end

  # GET /export_runs/1
  # GET /export_runs/1.json
  def show
    @export_run = ExportRun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @export_run }
    end
  end

  # GET /export_runs/new
  # GET /export_runs/new.json
  def new
    @export_run = ExportRun.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @export_run }
    end
  end

  # GET /export_runs/1/edit
  def edit
    @export_run = ExportRun.find(params[:id])
  end

  # POST /export_runs
  # POST /export_runs.json
  def create
    @export_run = ExportRun.new(params[:export_run])

    respond_to do |format|
      if @export_run.save
        format.html { redirect_to @export_run, notice: 'Export run was successfully created.' }
        format.json { render json: @export_run, status: :created, location: @export_run }
      else
        format.html { render action: "new" }
        format.json { render json: @export_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /export_runs/1
  # PUT /export_runs/1.json
  def update
    @export_run = ExportRun.find(params[:id])

    respond_to do |format|
      if @export_run.update_attributes(params[:export_run])
        format.html { redirect_to @export_run, notice: 'Export run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @export_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /export_runs/1
  # DELETE /export_runs/1.json
  def destroy
    @export_run = ExportRun.find(params[:id])
    @export_run.destroy

    respond_to do |format|
      format.html { redirect_to export_runs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/export_runs_helper.rb
module ExportRunsHelper
end

app/views/export_runs/_form.html.erb
<%= form_for(@export_run) do |f| %>
  <% if @export_run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@export_run.errors.count, "error") %> prohibited this export_run from being saved:</h2>

      <ul>
      <% @export_run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data_source_id %><br />
    <%= f.number_field :data_source_id %>
  </div>
  <div class="field">
    <%= f.label :started_at %><br />
    <%= f.datetime_select :started_at %>
  </div>
  <div class="field">
    <%= f.label :finished_at %><br />
    <%= f.datetime_select :finished_at %>
  </div>
  <div class="field">
    <%= f.label :record_count %><br />
    <%= f.number_field :record_count %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/export_runs/edit.html.erb
<h1>Editing export_run</h1>

<%= render 'form' %>

<%= link_to 'Show', @export_run %> |
<%= link_to 'Back', export_runs_path %>

app/views/export_runs/index.html.erb
<h1>Listing export_runs</h1>

<table>
  <tr>
    <th>Data source</th>
    <th>Started at</th>
    <th>Finished at</th>
    <th>Record count</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @export_runs.each do |export_run| %>
  <tr>
    <td><%= export_run.data_source_id %></td>
    <td><%= export_run.started_at %></td>
    <td><%= export_run.finished_at %></td>
    <td><%= export_run.record_count %></td>
    <td><%= export_run.duration %></td>
    <td><%= link_to 'Show', export_run %></td>
    <td><%= link_to 'Edit', edit_export_run_path(export_run) %></td>
    <td><%= link_to 'Destroy', export_run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Export run', new_export_run_path %>

app/views/export_runs/new.html.erb
<h1>New export_run</h1>

<%= render 'form' %>

<%= link_to 'Back', export_runs_path %>

app/views/export_runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data source:</b>
  <%= @export_run.data_source_id %>
</p>

<p>
  <b>Started at:</b>
  <%= @export_run.started_at %>
</p>

<p>
  <b>Finished at:</b>
  <%= @export_run.finished_at %>
</p>

<p>
  <b>Record count:</b>
  <%= @export_run.record_count %>
</p>

<p>
  <b>Duration:</b>
  <%= @export_run.duration %>
</p>


<%= link_to 'Edit', edit_export_run_path(@export_run) %> |
<%= link_to 'Back', export_runs_path %>